{"id":20212, "kind":"Bug", "createdAt":"2012-12-05T20:58:17.898392-08:00", "status":"Will not fix", "title":"Can't take database out of flash backup mode when using local-disk failover", "category":"xdmp", "severity":"Major", "priority":{"level":"1", "title":"Required for product release"}, "submittedBy":{"username":"dchander", "name":"Dinesh Chander", "email":"dinesh.chander@globallogic.com"}, "assignTo":{"username":"nobody", "name":"nobody nobody", "email":"nobody@marklogic.com"}, "description":"Reported in case #12191.\r\n\r\nWhen one tries to take a database out of flash-backup mode using API script, the script fails when local-disk failover is configured and the script is run with the same database as the context database. To make it work, one has to run the query against some other database which is not in flash backup mode.\r\nThe script works fine when local-disk failover is not configured.\r\n--------------------------------------------------------------------------------------------\r\nWayne Feick (Staff) Posted On: 03 December 2012 11:11 PM\r\n\r\nIt does strike me as odd that you get different behavior when local-disk  failover is configured than when it's not. If you can easily replicate \r\nat will, I'd be curious to see a log with the following trace flags enabled: Forest Replicate, Forest State, Forest Label.\r\nIf you could take a pstack movie while in a hung state, it would help to identify what the issue is.\r\n\r\nI don't have cycles to try and replicate this right now, but if either Mark or support can do this we may be able to understand why it's hanging and then decide if it's a bug. I'm pretty sure Mark is running in a secure environment that may make retrieving logs and stacks \r\ndifficult, so it probably makes more sense for someone in support to replicate the issue.\r\n\r\nThanks,\r\nWayne.\r\n--------------------------------------------------------------------------------------------", "samplequery":"I have setup a repro (using ML 5.0-4.1) on lab machines rh5-amd64-3 & rh5-amd64-10. When I don't configure local-disk failover, I can put the forest in \"all\" and \"flash-backup\" mode but when I enable local-disk failover, the script fails to put a forest (which is already in \"flash-backup\" mode) to \"all\" mode. To make it work, I had to change the context database (content source).\r\n\r\nAttached zip file contains the script, logs and pstacks.", "sampledata":"", "version":"5.0-4", "tofixin":"N/A", "fixedin":"N/A", "platform":"all", "memory":"", "processors":"", "note":"", "subscribers":[{"username":"dchander", "name":"Dinesh Chander", "email":"dinesh.chander@globallogic.com"}, {"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, {"username":"mhelmstetter", "name":"Mark Helmstetter", "email":"mark.helmstetter@marklogic.com"}, {"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, {"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}], "attachments":[{"name":"logs from duplicating the issue", "uri":"root/support/bugtracking/attachments/20212/12191.zip"}], "relationships":[{"type":"", "to":""}], "clones":[21338], "cloneOf":"", "support":{"headline":"", "supportDescription":"", "workaround":"", "publishStatus":"Not Ready", "tickets":["12191", " 12375"], "customerImpact":{"level":"Medium", "title":"Requires significant or unnatural effort to work around issue or to prevent significant business impact"}}, "tags":["xdmp", "dchander"], "changeHistory":[{"time":"2012-12-05T20:58:17.898392-08:00", "updatedBy":{"username":"dchander", "name":"Dinesh Chander", "email":"dinesh.chander@globallogic.com"}, "change":{"assignTo":{"from":{"username":"dchander", "name":"Dinesh Chander", "email":"dinesh.chander@globallogic.com"}, "to":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}}}, "files":[], "show":true}, {"time":"2012-12-05T21:39:46.209111-08:00", "updatedBy":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"Haitao, do you have a little time to look through the attached logs and see what they show?"}, {"time":"2012-12-05T21:39:46.209111-08:00", "updatedBy":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "change":{"assignTo":{"from":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "to":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}}}, "files":[], "show":true}, {"time":"2012-12-05T21:39:46.209111-08:00", "updatedBy":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "change":{"tofixin":{"from":"", "to":"5.0-5"}}, "files":[], "show":true}, {"time":"2012-12-23T00:06:20.300919-08:00", "updatedBy":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"I think the difference between the case with failover and the case without failover is that a database with all its MASTER forests in flash-backup is UNAVAILABLE. while a database with all its forests (no failover configured) in flash-backup is AVAILABLE.  This explains why the same script (query) works when running against other databases but doesn't work when running against THIS database.  \r\n\r\nI think the question here is whether it is a bug for a database to be UNAVAILABLE if all its MASTER forests are \"flash-backup\".    I created a database with one maser forest and one replica forest. When the master is in \"flash-backup\", both forests are in the wait-replication state (hence the database is UNAVAILABLE)."}, {"time":"2013-01-07T15:11:11.743131-08:00", "updatedBy":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"talked to Wayne. For a read-only/flash-backup forest, its label is empty hence it doesn't come out of the wait-replication state. This is non-trivial to fix. Given that there is a simple workaround for the issue, we are pushing the bug out to 5.0-6. "}, {"time":"2013-01-07T15:11:30.822911-08:00", "updatedBy":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, "change":{"tofixin":{"from":"5.0-5", "to":"5.0-6"}}, "files":[], "show":true}, {"time":"2013-01-14T20:43:44.361933-08:00", "updatedBy":{"username":"dchander", "name":"Dinesh Chander", "email":"dinesh.chander@globallogic.com"}, "change":{}, "files":[], "show":true, "comment":"Similar issue reported in support case #12375 but with Database replication.\r\n\r\nAfter configuring database replication, if we put the forest into flash-backup mode on the replica site then executing any query with that database as context database throws \"Forest not available: syncing replica\" error. If we do same at Master i.e. put the forest at the Master site to flash-backup mode and then execute any query at master site then it works fine."}, {"time":"2013-03-28T05:56:14.188494-07:00", "updatedBy":{"username":"derickson", "name":"David Erickson", "email":"David.Erickson@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"CMS ran into this one the day before going into production (yesterday) .  \r\n6.0-2.1 RHEL"}, {"time":"2013-03-28T07:22:51.104414-07:00", "updatedBy":{"username":"rjovanovich", "name":"Richard Jovanovich", "email":"richard.jovanovich@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"Cloned to 6.0 since I don't currently see one."}, {"time":"2014-02-23T21:43:53.256011-08:00", "updatedBy":{"username":"gvaidees", "name":"Ganesh Vaideeswaran", "email":"Ganesh.Vaideeswaran@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"Assigning as P1 since this is support reported"}, {"time":"2014-03-03T14:56:03.810673-08:00", "updatedBy":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"Fixed in v6. Customer reported on v5. Is v5 solution different/complex/risky?"}, {"time":"2014-03-03T15:00:51.215589-08:00", "updatedBy":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"Wayne fixed this on 6.0/7.0 so I am moving it to his queue."}, {"time":"2014-03-03T15:00:51.215589-08:00", "updatedBy":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, "change":{"assignTo":{"from":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, "to":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}}}, "files":[], "show":true}, {"time":"2014-03-03T15:00:51.615693-08:00", "updatedBy":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"Wayne fixed this on 6.0/7.0 so I am moving it to his queue."}, {"time":"2014-03-03T15:02:26.884353-08:00", "updatedBy":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"It was fixed in v6 under some other bug, so it'd take some archaeology to figure out which bug(s) that was and then back port the fix(es). I'd recommend pushing them to 6 rather than back porting to 5."}, {"time":"2014-03-03T15:02:26.884353-08:00", "updatedBy":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "change":{"assignTo":{"from":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "to":{"username":"hwu", "name":"Haitao Wu", "email":"haitao.wu@marklogic.com"}}}, "files":[], "show":true}, {"time":"2014-03-03T15:03:36.014559-08:00", "updatedBy":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"Looks like bugtrack undid Haitao's assignment to me. I'm going to assign to Rick to see if he agrees on not backporting."}, {"time":"2014-03-03T15:03:36.014559-08:00", "updatedBy":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "change":{"assignTo":{"from":{"username":"wfeick", "name":"Wayne Feick", "email":"wfeick@marklogic.com"}, "to":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}}}, "files":[], "show":true}, {"time":"2014-03-03T15:51:36.719368-08:00", "updatedBy":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}, "change":{}, "files":[], "show":true, "comment":"This bug was noticed by both RLSI & JPMC on v5.  We have queries out to these customers and will get back to you."}, {"time":"2014-03-04T09:30:10.705818-08:00", "updatedBy":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}, "change":{"status":{"from":"", "to":"Will not fix"}, "assignTo":{"from":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}, "to":{"username":"nobody", "name":"nobody nobody", "email":"nobody@marklogic.com"}}}, "files":[], "show":true, "comment":"RLSI is on v6 and JPMC is not using local disk failover anymore.\r\n\r\nOK NOT to backport\r\n\r\n-closing this bug as will not fix. "}, {"time":"2014-03-04T09:30:10.705818-08:00", "updatedBy":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}, "change":{"assignTo":{"from":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}, "to":{"username":"nobody", "name":"nobody nobody", "email":"nobody@marklogic.com"}}}, "files":[], "show":true}, {"time":"2014-03-04T09:30:10.705818-08:00", "updatedBy":{"username":"rpelton", "name":"Rick Pelton", "email":"rick.pelton@marklogic.com"}, "change":{"tofixin":{"from":"5.0-6", "to":"N/A"}}, "files":[], "show":true}], "updatedAt":"2014-03-04T09:30:10.705818-08:00", "renderDescriptionAs":"normal", "renderSampleQueryAs":"normal"}